from . import spo_info
from . import res_partner
from . import res_config_settings
from . import crm_lead
from . import sale_order
from . import product_template
from . import product_attribute_value
from . import sale_order_line_desembolso
from . import sale_order_line
from . import account_payment
from . import account_move_line